### ISSUE TITLE
[Suggestion] finishing crafting mechanics

### ISSUE THREAD

**Issue by shoverno2** [GrigLog/ThaumTweaks#33]
There's an option for quantity in alchemy and infusion
Like from infusion process there would be multiple items, not one
(for example "thaumic wonders")

But it was unfinished thaumcraft part
and infusion or alchemy
can't produce more then one item

So
If there's a quantity value
what about fixing this up to workstate?

An idea about multiple items pop up and droping near on infusion  finish...

**Comment by GrigLog** [comment]
Alchemy recipes allow specifying the amount. 
`ThaumcraftApi.addCrucibleRecipe(
            new ResourceLocation("thaumtweaks:test1"),
            new CrucibleRecipe("",
                new ItemStack(Items.DIAMOND, 2),
                new ItemStack(Items.STICK),
                new AspectList().add(Aspect.DESIRE, 5))
        );`
works fine. 
Infusion is a completely different story - arcane pedestals have a limit of 1 item in a held ItemStack. Making infusions return several items would mean changing the behaviour of pedestals, which would break a huge part of automatization for some players. And dropping items on ground is the worst thing possible because it is random, sometimes you could not pick up an item with a hopper. And it just feels wrong, like some error in a process. Plus I can hardly imagine when crafting several items per one infusion would be required as infusion is supposed to create powerful, expensive items. If you want something cheap - just use crucible or arcane workbench.
